//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CascadiaTxnPlugin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CascadiaTxnPlugin.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed External Addresses.
        /// </summary>
        internal static string AllowedExternalAddresses {
            get {
                return ResourceManager.GetString("AllowedExternalAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a comma-delimited list of addresses, or * to allow all.
        /// </summary>
        internal static string AllowedExternalAddressesToolTip {
            get {
                return ResourceManager.GetString("AllowedExternalAddressesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cascadia Transaction Server.
        /// </summary>
        internal static string CascadiaTransactionServer {
            get {
                return ResourceManager.GetString("CascadiaTransactionServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echo received data.
        /// </summary>
        internal static string Echo {
            get {
                return ResourceManager.GetString("Echo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send all received data back to the source.
        /// </summary>
        internal static string EchoToolTip {
            get {
                return ResourceManager.GetString("EchoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable keepalives.
        /// </summary>
        internal static string EnableKeepAlives {
            get {
                return ResourceManager.GetString("EnableKeepAlives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended to detect dropped client connections.
        /// </summary>
        internal static string EnableKeepAlivesToolTip {
            get {
                return ResourceManager.GetString("EnableKeepAlivesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local IP Address.
        /// </summary>
        internal static string Interface {
            get {
                return ResourceManager.GetString("Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify which IP address to listen on or use 0.0.0.0 for all interfaces.
        /// </summary>
        internal static string InterfaceToolTip {
            get {
                return ResourceManager.GetString("InterfaceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Port.
        /// </summary>
        internal static string LocalPort {
            get {
                return ResourceManager.GetString("LocalPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local port {0} already in use.
        /// </summary>
        internal static string LocalPortInUse {
            get {
                return ResourceManager.GetString("LocalPortInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector instance will listen on this port.
        /// </summary>
        internal static string LocalPortToolTip {
            get {
                return ResourceManager.GetString("LocalPortToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cascadia Technology LLC.
        /// </summary>
        internal static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6c41793e-4f7b-450c-a1ff-8ff258d5ffa3.
        /// </summary>
        internal static string PluginId {
            get {
                return ResourceManager.GetString("PluginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cascadia Transaction Server.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
    }
}
